<a href="https://colab.research.google.com/github/e8035669/pytorch_learning/blob/master/basic/learn_pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip3 install torch torchvision

In [0]:
import torch

In [0]:
x = torch.empty(5,3)
print(x)

tensor([[1.4951e-35, 0.0000e+00, 2.3618e-16],
        [2.4832e-16, 2.9388e-39, 2.9388e-39],
        [2.9388e-39, 2.9388e-39, 2.9388e-39],
        [2.9388e-39, 2.9388e-39, 2.9388e-39],
        [2.9388e-39, 2.9388e-39, 1.1388e-38]])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0574, 0.5695, 0.0469],
        [0.8660, 0.7155, 0.7016],
        [0.6127, 0.5724, 0.2929],
        [0.0610, 0.4755, 0.0938],
        [0.1086, 0.0808, 0.7381]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9327,  0.6674,  0.8193],
        [-0.1267, -1.4513,  0.0765],
        [-0.4913, -0.1592, -0.6308],
        [ 1.1919,  0.3471,  0.2814],
        [-0.5643, -0.9128,  0.0381]])
torch.Size([5, 3])


In [0]:
y = torch.rand(5, 3)

In [0]:
print(x + y)
print(torch.add(x, y))

tensor([[ 2.8709,  0.7795,  1.5126],
        [ 0.2752, -1.2126,  0.9182],
        [-0.4537, -0.0747, -0.0152],
        [ 1.3360,  0.8255,  0.5414],
        [-0.5398, -0.7711,  0.1537]])
tensor([[ 2.8709,  0.7795,  1.5126],
        [ 0.2752, -1.2126,  0.9182],
        [-0.4537, -0.0747, -0.0152],
        [ 1.3360,  0.8255,  0.5414],
        [-0.5398, -0.7711,  0.1537]])


In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[ 2.8709,  0.7795,  1.5126],
        [ 0.2752, -1.2126,  0.9182],
        [-0.4537, -0.0747, -0.0152],
        [ 1.3360,  0.8255,  0.5414],
        [-0.5398, -0.7711,  0.1537]])


In [0]:
y.add_(x)
print(y)

tensor([[ 2.8709,  0.7795,  1.5126],
        [ 0.2752, -1.2126,  0.9182],
        [-0.4537, -0.0747, -0.0152],
        [ 1.3360,  0.8255,  0.5414],
        [-0.5398, -0.7711,  0.1537]])


In [0]:
print(x)
print(x[0, :])

tensor([[ 1.9327,  0.6674,  0.8193],
        [-0.1267, -1.4513,  0.0765],
        [-0.4913, -0.1592, -0.6308],
        [ 1.1919,  0.3471,  0.2814],
        [-0.5643, -0.9128,  0.0381]])
tensor([1.9327, 0.6674, 0.8193])


In [0]:
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
z = x.view(-1, 8)
print(z)
print(x.size(), y.size(), z.size())

tensor([[-0.1642, -0.8975, -0.2236, -1.2245],
        [-1.4289,  0.9404,  1.1675, -0.9267],
        [-0.0733, -2.4174, -1.2378, -1.8223],
        [ 1.4877,  0.2075, -0.5342, -1.4796]])
tensor([-0.1642, -0.8975, -0.2236, -1.2245, -1.4289,  0.9404,  1.1675, -0.9267,
        -0.0733, -2.4174, -1.2378, -1.8223,  1.4877,  0.2075, -0.5342, -1.4796])
tensor([[-0.1642, -0.8975, -0.2236, -1.2245, -1.4289,  0.9404,  1.1675, -0.9267],
        [-0.0733, -2.4174, -1.2378, -1.8223,  1.4877,  0.2075, -0.5342, -1.4796]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2450])
-0.2449859380722046


In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]


In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
torch.cuda.is_available()

True

In [0]:
device = torch.device("cuda")
print(type(device), device)

<class 'torch.device'> cuda


In [0]:
y = torch.ones_like(x, device = device)
x = x.to(device)
z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([0.7550], device='cuda:0')
tensor([0.7550], dtype=torch.float64)
